name: "Raspotify"
description: "Raspotify"
version: "0.0.1"
slug: "raspotify"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
homeassistant_api: true
ports:
  8000/tcp: 8000
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int
